### ISSUE TITLE
Missing function prototype in julia.hpp

### ISSUE THREAD

**Issue by jeremych1000** [HPCE/hpce-2017-cw1#1]
Environment: WSL

Expected: successful compile

What happens:

```
jeremych@JEREMY-PC:/mnt/c/Users/Jeremy/Documents/GitHub/hpce-2016-cw1$ make
g++ -o bin/julia -W -Wall -std=c++11 -Wno-unused-parameter -I include -pthread src/julia_frame_reference.cpp src/julia_frame_parallel_inner.cpp src/julia_frame_parallel_outer.cpp src/julia_frame_parallel_both.cpp src/julia_driver.cpp
src/julia_driver.cpp: In function ‘int main(int, char**)’:
src/julia_driver.cpp:283:29: error: ‘juliaFrameRender_ParallelBoth’ was not declared in this scope
                 juliaEngine=juliaFrameRender_ParallelBoth;
                             ^
make: *** [bin/julia] Error 1
```

Solution:
Add void juliaFrameRender_ParallelBoth() to julia.hpp
Create /bin

**Comment by narobertson42** [comment]
void juliaFrameRender_ParallelBoth(
                                   unsigned width,     //! Number of pixels across
                                   unsigned height,    //! Number of rows of pixels
                                   complex_t c,        //! Constant to use in z=z^2+c calculation
                                   unsigned maxIter,   //! When to give up on a pixel
                                   unsigned _pDest     //! Array of width_height pixels, with pixel (x,y) at pDest[width*y+x]
);

**Comment by m8pple** [comment]
Well that's a good start. Sigh. Thanks.

At least this gives me a chance to see if my "pull request to everyone" script actually works.
