### ISSUE TITLE
CW1 - Turning on optimisations

### ISSUE THREAD

**Issue by SantiagoRubioDev** [HPCE/hpce-2017-cw1#10]
After making the first two graphs, I tried getting a "release" build instead of a "debug" build by commenting out the line:
         `# CPPFLAGS += -DNDEBUG=1 -03`
I also commented out the line:
         `# LDLIBS += ltbb`
After saving the modified makefile I run the command
         `make bin/julia`
and I get:
        `make:    ´bin/julia' is up to date.`
when I run bin/julia I get the same execution time as before.

What is the command to overwrite the previous "debug" build?

**Comment by m8pple** [comment]
Ah, good question, my bad.

The `-B` flag will tell make to ignore the timestamps.

So:

```
make -B bin/Julia 
```

Other alternatives are to edit the source file to change the timestamp.
There is a tool called `touch` which makes a file look newer:

```
touch src/julia_driver.cpp
make bin/Julia
```

would also work.

(I'll link this issue from the readme, and close it from there)
