### ISSUE TITLE
"tbb/parallel_for.h" file not being found for parallel inner

### ISSUE THREAD

**Issue by Gar1G** [HPCE/hpce-2017-cw1#13]
Platform: Mac OS
Installed tbb using homebrew.

Im trying to make bin/julia with the updated julia_frame_parallel_inner.cpp but I am getting the following error:
src/julia_frame_parallel_inner.cpp:2:10: fatal error: 'tbb/parallel_for.h' file not found

I have found the tbb folder in the /usr/local/include/ directory of my mac but this doesn't to be found when compiling. 
Any help resolving is much appreciated

**Comment by jeremych1000** [comment]
Check your makefile, is LDLIBS += -ltbb uncommented?

**Comment by narobertson42** [comment]
Run `gcc -v`

You should see something similar to this

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`
```

If your `--with-gxx-include-dir` is not `/usr/include/c++/4.2.1` run `xcode-select --install` follow the dialogue and then the error should be resolved

If it still doesn't work install tbb with homebrew not macports, `brew install tbb`
