### ISSUE TITLE
Evaluating the speed-up (formula)

### ISSUE THREAD

**Issue by gpapas11** [HPCE/hpce-2017-cw1#14]
Hello guys,
So the way I think of it I'd like to calculate a speedup value like this :
Speedup = |time_after_optimization - time| / time

However I found this on the Internet:
# Speedup = T1/TN; where T1 and TN are the wall clock time for 1 and N threads, respectively.

Doing it the second way I suppose it should be like 
speedup = time / time_after_optimization

Did you guys go for the second formula?

**Comment by m8pple** [comment]
This is a good question, and a good point for any scientific/disciplined presentation
of performance changes.

If I were to say "I have optimised some code, and it is now 3x faster", it is pretty
unambiguous what it means:

```
TN = T1 / 3
```

or (equivalently):

```
TN * 3 = T1
```

If I say it is 200% faster, then it becomes a bit unclear, it could be:

```
T1 = TN * 2
```

or (not equivalently):

```
T1 = TN * (1 + 2)
```

So generally one should avoid talking about percentage changes in performance.

The first alternative you suggest is actually the relative change in execution
time, which is again a slightly different measure (though one should avoid the
|.| as it assumes that optimisations always makes things better, but sometimes
they make things worse).

So I would always stick with the T1 / TN definition as the first definition of
speed-up - it is (fairly) unambiguous.

(Another useful metric is the relationship between N (number of cores/threads)
and the speedup achieved, but that is usually called scaling - if the ratio
is close to 1 (speedup of N times for N processors) then you have perfect scaling).

**Comment by gpapas11** [comment]
Thanks a lot :)
