### ISSUE TITLE
TBB Issues with MacPorts

### ISSUE THREAD

**Issue by pm1113** [HPCE/hpce-2017-cw1#17]
I had massive troubles troubleshooting TBB when installed with Macports. 

Seems to work smoothly when installed via Homebrew.

Suggest changing readme_os_x.md

**Comment by m8pple** [comment]
Looks like people agree, so I'll change the suggested order.

Can you remember what exactly went wrong?

I used TBB on mac ports over the summer (no experience with brew), and as far as I recall:

```
sudo port install tbb
```

worked ok.

**Comment by pm1113** [comment]
I was getting the following error when compiling:

`Undefined symbols for architecture x86_64`

Error when away when I uninstalled TBB with macports and installed it with homebrew.

**Comment by m8pple** [comment]
Hrmm, ok. Yup, no idea what that is :)

(My experience of trying to do dev work with OS X over the summer was that being
"almost Unix, except not-quite" was actually worse than the "definitely not Unix"
feel on Windows. While I didn't mind the OS X GUI, I found that for serious
work I was always spinning up a VM - in which case I might as well stick with
windows, keyboard muscle memory is a powerful thing)
