### ISSUE TITLE
"make clean" doesn't work

### ISSUE THREAD

**Issue by lynx5120** [HPCE/hpce-2017-cw1#18]
I just run `make clean` as the [Subbmission part](https://github.com/HPCE/hpce-2016-cw1#submission) said. But my terminal shows:

> make: **\* No rule to make target `clean'. Stop.

I guess there should be something in makefile like:

> clean:
>   rm  [something to remove]

So what should I do next?

**Comment by jeremych1000** [comment]
Try 
clean: 
rm - rf bin/julia; make bin/julia

**Comment by patengelbert** [comment]
clean should be something like 

``` make
clean:
\# This removes the whole compiled output folder (@ suppresses the command from terminal)
\# Also remember to change the spaces to a tab
    @rm -rf bin/
```

**Comment by m8pple** [comment]
Sorry, my fault - I was confusing the conceptual `make clean` (i.e. clean up the
binaries/objects), with the literal `make clean` (which is the make target that
I didn't put in).

I'll adapt @patengelbert 's suggestion, though I'm less keen on nuking the 
whole directory. So I'll only clean up the directory, and also remove the `@`
surpression (particularly for people new to make it is useful for them to
see what is happening).
