### ISSUE TITLE
tbb issue when compiling julia_frame_parallel_inner

### ISSUE THREAD

**Issue by gpapas11** [HPCE/hpce-2017-cw1#19]
I get this error when running make -B /bin/julia after implementing parallelism to the inner loop
and the problem seems to be in including the header:

fatal error: tbb/parallel_for.h: No such file or directory

Has anybody come across the same problem?

p.s 
(I have uncommented the:  LDLIBS += -ltbb 
and the libtbb-dev is installed)

**Comment by m8pple** [comment]
What platform are you running this under, is it linux, OS X, or something else?

Sometimes the headers get put in odd places, depending on the particular
system. You can often go hunting for it by trying different system locations,
such as:

```
/usr/include
/usr/local/include
/opt/include
```

If you can find where your system has put the tbb directory, you can add
it to your makefiles search path. For example, if you fine the path is:

```
/user/local/include/tbb/parallel_for.h
```

Then you could add the line:

```
CPPFLAGS += -I /user/local/include
```

**Comment by gpapas11** [comment]
thank you very much

**Comment by m8pple** [comment]
Would you mind posting something about how the problem was resolved? It might
be useful for other people who have a similar problem.

**Comment by gpapas11** [comment]
It seems I didn't have this header in any directory (platform : Ubuntu), even if after running
$ apt-cache search tbb  I got the following:

```
libthrust-dev - Thrust - Parallel Algorithms Library
libtbb-dev - parallelism library for C++ - development files
libtbb-doc - parallelism library for C++ - documentation
libtbb2 - parallelism library for C++ - runtime files
libtbb2-dbg - parallelism library for C++ - debugging symbols
tbb-examples - parallelism library for C++ - example files
```

So I "sudo apt-get install"ed libtbb-dev (thanks to adreamisfud).
