### ISSUE TITLE
How to setup ffmpeg on Mac with ffplay

### ISSUE THREAD

**Issue by narobertson42** [HPCE/hpce-2017-cw1#2]
brew install ffmpeg --with-fdk-aac --with-ffplay --with-freetype --with-libass --with-libquvi --with-libvorbis --with-libvpx --with-opus --with-x265

It can take up to 10 minutes

**Comment by m8pple** [comment]
Thanks. I fear the visual payoff is not quite worth the 10 minutes, but still :)
