### ISSUE TITLE
Bug in test_submission.sh

### ISSUE THREAD

**Issue by jeremych1000** [HPCE/hpce-2017-cw1#24]
**Env**: WSL 4e73a6beec684b3bea9c0f26f563863982bb03b0

**Command**: ./test_submission.sh jc4913 ./jc4913.zip

**Expected**: Run test

**Actual**: ./test_submission.sh: line 58: ANCHOR_DIR: command not found
**Console**:
`jeremych@JEREMY-PC:/mnt/c/Users/Jeremy/Documents/GitHub/hpce-2016-cw1-jc4913$ ./test_submission.sh jc4913 ./jc4913.zip
Working directory is ./working/ZPPdkq
Unzipping into ./working/ZPPdkq
Looking for the readme.md file.
./test_submission.sh: line 58: ANCHOR_DIR: command not found
Cleaning the bin directory (just in case).
Force building bin/julia.
make: *** No rule to make target`bin/julia'. Stop.
Warning : make: `bin/julia' is up to date. seems to have failed.
Error (Fatal) : make:`bin/julia' is up to date. did not result in a file called /bin/julia`

**Cause**: Line 58: ANCHOR_DIR = ${WORKING_DIR};

**Solution**: ANCHOR_DIR=${WORKING_DIR}; (no space!)

**Comment by m8pple** [comment]
Gah, you can tell all my test .zips had a sub-directory. Thanks.

Does it work ok apart from that?

**Comment by jeremych1000** [comment]
Yes (passed 20/24 for now), apart from 
## Begin test 16
FAIL, File results/max_iter_versus_time.pdf exists.

Fail because it exists? or doesn't exist?

**Comment by m8pple** [comment]
Ah, yes that is ambiguous. The test is "does the file exist", and it fails that test.

I'll change the test description to "Check whether file results/max_iter_versus_time.pdf exists."
