### ISSUE TITLE
Max Frames -animation

### ISSUE THREAD

**Issue by narobertson42** [HPCE/hpce-2017-cw1#29]
Should the -animation flag be set when scaling Max Frames?

**Comment by m8pple** [comment]
Yes. Oh - I see, the default is the single frame view. The intent was
to see scaling with time.

I must have unconsciously added the flag when doing my run through the script.

I'll add a note saying that ideally animation should be turned on, but that
it doesn't matter if people have already done the graphs.

Thanks.

**Comment by jeremych1000** [comment]
I've already done the graphs but should be relatively simple to redo... on that note, will the marking for this coursework only be done on whether the graphs have been produced? Will you take a look at each graph to make sure we didn't just generate blank files with <filename>.pdf?
