### ISSUE TITLE
User and Sys time are not changing

### ISSUE THREAD

**Issue by aliaasif** [HPCE/hpce-2017-cw1#30]
I am running julia.exe with various parameter sizes but get the same user and sys times despite variations.
_user    0m0.000s
sys     0m0.015s_

I'd expect these values to change with each variation so why am I obtaining otherwise?

Note that real time is corresponding to the changes as expected. I am running the executable through Git Bash on Windows using commands like,
_$ time ./julia.exe -height 10 -width 10 > /dev/null_

Any help would be much appreciated. 

Thanks!

**Comment by aliaasif** [comment]
Resolved by working with Linux now but I'd still like to understand why it didn't work in Windows

**Comment by m8pple** [comment]
Depending on the implementation of the shell, it might not have anything hooked into
the appropriate OS timing functions, though it would be a bit surprising. It also might
be that the resolution of the timing information is always too short.

Was the real-time you saw fairly substantial, e.g. 1sec or more?

I tried git bash shell, and did:

```
time find
```

and it showed up as using positive user and sys time (though much less
than real time).
