### ISSUE TITLE
No mention of linking TBB libraries in "Making things parallel"

### ISSUE THREAD

**Issue by ppp2211** [HPCE/hpce-2017-cw1#32]
I'm working through the guide right now, and I got slightly stuck on the "Making things parallel" part with the compiler spitting out a large list of tbb-related errors. 

Then, with help of Google, I realised I'm not importing the TBB libraries into the compiler. A quick look in the makefile confirmed my suspicion - "LDLIBS += -ltbb" is commented out by default, and there's no mention of this in the tutorial. 

I feel like it would be a good idea to add a sentence reminding us to go back and update the makefile before trying to recompile for TBB, unless this is a deliberate attempt to make people learn how to debug (i.e. Google the errors).

**Comment by Matthewar** [comment]
Is there anything mentioning installing the library too? I had to find the repo for ubuntu (which turned out to be libtbb-dev), but I couldn't see it mentioned anywhere - that might also be useful since some people won't have used the linux package manager much.

**Comment by ppp2211** [comment]
Yes - that is under "Choose a platform" -> "Installing libraries". At least in the Linux platform description, haven't bothered checking any other ones.

Different distros will have different TBB package names, but the Ubuntu/Debian one is actually listed. For Arch it was intel-tbb.

**Comment by m8pple** [comment]
That looks like a regression on my part, as I don't think it was a problem last time. The reason
for having it un-commented to start with is that it allows people to get started before getting
TBB installed. It used to be that compiling TBB was part of the spec, but this was too much for
a lot of people.

I'll update the instructions, as it is definitely a non-obvious step for most people and should
be in there.

Thanks.

**Comment by m8pple** [comment]
(Leaving the issue open for a while, so that people can see it.)
