### ISSUE TITLE
brew install ffmpeg flags

### ISSUE THREAD

**Issue by filangelos** [HPCE/hpce-2017-cw1#33]
Please update the installation flags, to accommodate deprecations:
```
Warning: ffmpeg: --with-ffplay was deprecated; using --with-sdl2 instead!
Warning: ffmpeg: this formula has no --with-libquvi option so it will be ignored!
```

updated command:
`brew install ffmpeg --with-fdk-aac --with-sdl2 --with-freetype --with-libass --with-libvorbis --with-libvpx --with-opus --with-x265`

**Comment by m8pple** [comment]
Thanks, I'll update them. If you see any other problems with
suggested brew / OSX commands then let me know, as they are all due to
past student contributions.
