### ISSUE TITLE
Provided environment for Windows not available

### ISSUE THREAD

**Issue by JB515** [HPCE/hpce-2017-cw1#34]
Thanks for offering a 'ready to go' environment for those of us on Windows. Unfortunately, I get the following when I log into Box:

"This shared file or folder link has been removed or is unavailable to you."

Do I need permission to access it or has the file been moved?

**Comment by m8pple** [comment]
It looks like Box (or Imperial) changed access flags. I've tried to open it up
as wide as possible again, can you give it another go?:
https://imperialcollegelondon.app.box.com/v/HPCE-2017-mingw64-tbb-opencl

I usually try to download under a private chrome tab, but it's possible I forgot
when testing, so may have picked up some ambient authentication with Box
from my browser.

There is also an older (but still perfectly usable) version from last year that
people were able to get last year:
https://imperialcollegelondon.app.box.com/v/HPCE-2016-mingw64-tbb
Main difference is that it has older versions of the compiler, but apart
from that it should be about the same (and is ~100MB smaller).

**Comment by JB515** [comment]
Working now, thanks.
