### ISSUE TITLE
Parallel_for argument types

### ISSUE THREAD

**Issue by Matthewar** [HPCE/hpce-2017-cw1#35]
I was getting the error `error: no matching function for call to ‘parallel_for(int, unsigned int&, juliaFrameRender_ParallelInner(unsigned int, unsigned int, complex_t, unsigned int, unsigned in
t*)::<lambda(unsigned int)>)’` when trying to add the first parallel loop from 0 to width.
The issue seems to be that the value 0 isn't an unsigned integer, but a normal integer, so I had to static cast it to 0 IE `static_cast<unsigned>(0)`
Is there a better way of doing this?

**Comment by ppp2211** [comment]
Type 0u instead of 0.

**Comment by Matthewar** [comment]
Nice, cheers.
