### ISSUE TITLE
How to use Blackboard?

### ISSUE THREAD

**Issue by giuliojiang** [HPCE/hpce-2017-cw1#36]
Sorry this might be a stupid question for most but computing students don't use blackboard so we have no idea how to use it.
I can see the course High Performance Computing for Engineers (2017-2018), but how to submit CW1?

**Comment by m8pple** [comment]
All the EIE students are now rolling about on the floor laughing, shouting "CATE!".
There are no stupid questions, only stupid VLEs.

The assessments are available off to the left, under Assessments. You'll see a link
to CW1, and you can submit it there.

(It's possible the link was not visible to students till just now - it looked like it
to me, but I recreated just in case. Nobody really knows how blackboard works).

**Comment by giuliojiang** [comment]
ok I see the upload page

thanks
