### ISSUE TITLE
make bin/julia doesn't seem to work

### ISSUE THREAD

**Issue by m8pple** [HPCE/hpce-2017-cw1#39]
> Do I need to install anyhing beforehand since the command " make bin/julia" doesn't seem to work

**Comment by m8pple** [comment]
I'm afraid this needs more information:
- What is your environment (Linux, OSX, MinGW, other)?
- How did you install or get your environment?
- What have you installed already?
- How/where were you typing the command?
- What do you mean by "doesn't seem to work", is there an error message?

**Comment by ys7914** [comment]
I have the same issue.

I used Windows with MinGW (with gcc and g++) and git installed. I have set the environment variables properly so gcc and g++ works. I made a copy of mingw32-make.exe and renamed it to make.exe in the C:\MinGW\bin folder.

I navigated to some folder through cmd.exe, cloned the hpce-2017-cw1 folder from github using **git clone [link]** command. And tried to execute the **make bin/julia** command. It throws an error.
<img width="960" alt="cw1-issue1" src="https://user-images.githubusercontent.com/25391124/31632528-1e732048-b2b5-11e7-8d6c-85ac10da4936.png">

How do I solve this problem?

**Comment by m8pple** [comment]
If you start the environment via `cmd`, then you are not really in the mingw environment. It will
be the windows environment, with the mingw tools on the path. My guess is that this is
causing mingw to think it is targeting windows, so the wrong platform logic is getting
selected in the julia program.

If you are using the pre-built mingw environment, try running mingw by running
`runme.bat` in the mingw folder, and you should end up with a mingw terminal.
It will have colours like the terminal I used in the first lecture, and when it builds
should like this (except using your repository URL, not the master):
![image](https://user-images.githubusercontent.com/3024705/31633074-152c5232-b2b7-11e7-87a7-15564cc691ce.png)

**Comment by ys7914** [comment]
Umm, I still have the same issue.
<img width="960" alt="cw1-issue2" src="https://user-images.githubusercontent.com/25391124/31633845-8b5d860e-b2b9-11e7-9251-ac64025027d2.png">

**Comment by m8pple** [comment]
The error with `_fileno` seems to be due to it not getting a windows specific version of
`stdio.h`, which usually comes with the mingw version.

The error with `std::thread` looks like it is a version of gcc/mingw that has not been built
with thread support, though that shouldn't be the case for the pre-built version.

Could you check:
- Where exactly did this mingw come from? If it is not from the pre-canned environment,
   which site did it come from (there are a few variants of mingw)?
- Are the manually changed environment variables still in place? If so, they should be removed, then
  restart mingw.
- It would be best to undo the manual replacement of `make` in the bin directory, and install it
   using the package manager:
   ````
   pacman -S make
   ````
   (Note that the pre-built mingw should actually have make installed, at least since the 13th,
   though you may have grabbed an older one.)
- Where is the version of g++ that is getting executed? Could you attach the output of
   ````
   which g++
   ````
   and
   ```
   g++ -v
   ````

**Comment by ys7914** [comment]
I think there was something wrong with my MinGW. I tried again with the canned version and it works. Thank you for your help
