### ISSUE TITLE
Mac OS - Tests 11 and 14 always failing in test_submission.sh

### ISSUE THREAD

**Issue by al2114** [HPCE/hpce-2017-cw1#41]
#27 

This issue still persists on the current revision of the script, is changing the script to utilise `gdate` from `coreutils` still valid for this assessment?

**Comment by eliasbenussi** [comment]
Ditto. Mac OS, same issue, the`gdate` fix solves the problem.

**Comment by m8pple** [comment]
Yes, that's still a valid fix. 

The script never got updated, as I never laid hands on a new mac for testing purposes, so couldn't be sure about any auto detection logic.

**Comment by daniel-grumberg** [comment]
Is it cool to submit a script that uses gdate? As in will you be running the one that comes with the submission?

**Comment by m8pple** [comment]
Yes, you can change _your_ version of `test_submission.sh`, as I'll be
using a clean/original version that still works in Linux.

The makefile you need to be more careful about changing though, as
in the script I rely on your makefile - so if there are any strange
mac-isms in there then they won't work. However, as far as I'm aware
nothing weird needs to be done to to get it compiling under OSX,
it's only the testing.
