### ISSUE TITLE
Will time change when rerunning code with different programs in the background? Replotting of performance graphs

### ISSUE THREAD

**Issue by bngzl** [HPCE/hpce-2017-cw1#43]
Hi, 

I have noticed that rerunning the same code on different days cause the timings to fluctuate quite significantly (by ~0.4s). For example, I ran the code sequentially at -o3 previously and it was 0.4s faster than running the exact same code sequentially at the same settings today. Nonetheless, the relative speedups shown by optimisation and parallelisation are still evident. 

Could this be due to the slightly different programs running in my computer's background? If so, if I had plotted my original non-optimised and non-parallelised graphs previously, must I replot them to better represent the relative increase in speed? 

Thank you!

**Comment by m8pple** [comment]
You will see differences between runs, and that can definitely be affected by things
like programs running in the background. It's worth trying to control the environment
as much as possible when doing these kinds of experiments, so try to disable anything
that looks CPU intensive. But there are a huge number of potential confounding
factors:
- "smart" programs, which try to wait until you (the user) are not "doing stuff" (i.e.
   using the mouse or keyboard) before use the CPU
- "dumb"/buggy programs, which take up CPU time when you use the mouse or
  keyboard. Many laptops have a "Synaptic" touchpad, and their default software
  drivers are notoriously high CPU when you are moving the pointer via the touchpad.
- IO intensive traffic, such as file transfers, which appear to use little CPU, but are
   actually causing lots of interrupts and context switches in the background. Things
   like drop-box and google sync can be a problem there, or other things doing
   network operations.
- Power state changes: laptops are very likely to report different speeds when on power
   versus on battery, and there are all kinds of heuristics an rules governing when
   clock frequency goes up.
- Heat management: if you run lots of programs, eventually your computer may get
   hot enough it starts to throttle the CPU. This can cause really weird effects if you
   have a computer with a clogged up fan, as it may appear to run faster at night
   (when it is cooler).

I'll stop there - the message is that it can be almost impossible to get reliable
repeat runs outside of a dedicated hardware perf testing lab. This is particularly
problematic on a machine with a GUI.

With respect to re-plotting the graphs - no, I wouldn't worry about that if the difference
is small. The main purpose of this activity is to think about how you should measure
performance, and to look for these kinds of changes. A few people have noticed
these kinds of changes or odd issues, and by doing so you are engaging with
the real purpose of creating the graphs - it isn't the graphs themselves, as much
as the process of thinking about measuring performance scaling and developing
skills for doing it.

So you may want to spend some time thinking about where the performance
difference came from, and seeing if you can experimentally isolate it.
