### ISSUE TITLE
Graphs in LibreOffice

### ISSUE THREAD

**Issue by Matthewar** [HPCE/hpce-2017-cw1#44]
The "Export to PDF" option in LibreOffice seems to generate a PDF for the entire sheet, including data - is this acceptable or is there a way to export the graphs on their own?

**Comment by m8pple** [comment]
I don't mind too much if there is some extra stuff on there, as long as the graph is clearly
visible.

However, it's worth working out how to export things like graphs in a vector form for use
in final year reports. LibreOffice makes it a bit painful as it doesn't support the idea of
a chart as a sheet in the same way as Excel, but you can get the same effect by copying
the graph, pasting it into a new sheet, and then only exporting that sheet to pdf:
https://forum.openoffice.org/en/forum/viewtopic.php?f=9&t=45304

(I suppose one can do project reports in Word, then it can all be done by OLE, but
my memory is long enough to remember the bad-old days of silently corrupted
OLE containers. Plus version control of Word documents is a massive pain.)
