### ISSUE TITLE
Confusion about 3rd and 4th task

### ISSUE THREAD

**Issue by hl5814** [HPCE/hpce-2017-cw1#45]
> Task3: Re-generate the maximum iteration scaling performance from earlier, and plot a graph of the absolute release execution times versus the debug execution times (seconds on the y scale). Save it as a graph called results/release_max_iter_versus_time.pdf.
> 
> Task4: Re-generate the dimension scaling performance from earlier, and plot a graph of the release execution speed-up compared to the debug execution times (speed-up on the y scale). Save it as a graph called results/release_dimension_versus_speedup.pdf.

From my understanding, Task 3 is asking us to plot x-axis -> max_iteration, y-aixs->time, and the chart should contain 2 data series (one with compiler optimisation and one without)

Task 4 is asking us to plot x-axis-> dimension, y-aixs-> speed_up?
what exactly does speed-up mean in this question, is it the difference in runtime between the optimised version and non-optimised one? Thank you.

**Comment by m8pple** [comment]
Speed-up here is in the [computer science sense](https://en.wikipedia.org/wiki/Speedup),
so it is the ratio between the original time and the new time. So if you get a new execution
time that is half the original time, you have a speed-up of 2 (as it is twice as fast).

The _difference_ in runtime would results in an absolute difference, so it would still be
in the same units (i.e. time). We want relative speed-up, which is a dimension-less number.
