### ISSUE TITLE
installing tbb on university machines

### ISSUE THREAD

**Issue by pjlehmann** [HPCE/hpce-2017-cw1#49]
I would like to install tbb on the university machines on ubuntu, but this does not work since I do not have superuser rights. Is there a workaround to this?

**Comment by obrown** [comment]
You might be able to build it from source in your own directory and set LD_LIBRARY_PATH, LIBRARY_PATH and CPATH so the compiler can find it.

**Comment by pjlehmann** [comment]
thank you very much for your answer. It kind of works as I do not get compiler errors. But I get linker errors now. 
The error is:
/usr/bin/ld: cannot find -ltbb

so I guess I should specify somehow where the library can be found, but I don't know where that is.
I also attached the makefile:

[makefile.txt](https://github.com/HPCE/hpce-2017-cw1/files/1391528/makefile.txt)

**Comment by pjlehmann** [comment]
ok so I figuered that out. I think I might have forgotten to build before and now I found the library and can link it in. The problem now is, that upon running julia I get the error:
bin/julia: error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory

This should be prevented by LD_LIBRARY_PATH right? Have I used it incorrectly in the makefile? Or do you have another suggestion?

**Comment by obrown** [comment]
LD_LIBRARY_PATH is for dynamically linked libraries, so it is consulted when you actually execute the program. You'll probably need to export it as a variable in the shell you run the program in. Might also be worth checking that modifying the Makefile won't interfere with any automated submission testing.

**Comment by pjlehmann** [comment]
WOW!!! It works. Thank you so very much. I didn't understand that I had to run the export and LD_LIBRARY_PATH as commands in the shell. I'll check if it works with the submission testing.
Thank you once more :)
