### ISSUE TITLE
Dump real output of time bin/julia in csv file

### ISSUE THREAD

**Issue by natoucs** [HPCE/hpce-2017-cw1#50]
I can not find a simple set of bash commands that can select the real time output of time bin/julia and dump it into a csv file. 

The writing or appending a value to csv file is straightforward but I am stuck on the earlier part (selecting only the real time output).

Has anyone succeeded in doing this ?

**Comment by obrown** [comment]
Are you accidentally using the shell builtin time rather than the GNU version of time? The command 'type time' should tell you this.

The GNU version [can take a format string](https://linux.die.net/man/1/time) which would allow you to select the real time output really easily.

**Comment by natoucs** [comment]
'time is a shell keyword' -> I guess I am using the shell built-in time.

But there is no problem in doing so right ? (apart from not taking format string)

Thanks obrown!

**Comment by guigzzz** [comment]
an example on how to do this is: `/usr/bin/time -f "%e" ./bin/julia > /dev/null 2> file.csv`

To use the GNU time, you need to fully qualify the path, like I have done. Time also doesn't output to `stdout` but rather to `stderr`. This above comand will pipe the output of `julia` to `/dev/null` and the output of the time command to `file.csv`. It is then just of matter of wrapping this in a for loop. Check out  `man time` for output formatting and other information (the format here outputs only the real time in seconds)

**Comment by m8pple** [comment]
This is a perennial problem, as there is no completely platform portable way of doing
this, particularly if you want decent time resolution. This is actually the reason for the
wierd use of `date` in the test script.

The solution suggested by @obrown works well if you know what version of time
you have. The full command given by @guigzzz works well (though note that you
want to append to the file using `>>` if you use it in a loop). You can also use the
`-o` option of many versions of time, so something like:
````
/usr/bin/time -f "%e" -o file.csv ./bin/julia > /dev/null
````
So you turn them into loop versions using something like this (haven't tested this):
````
widths="10 20 30 40 50"
echo "Width, Time" > line.csv
for w in $(widths) ; do
    /usr/bin/time -f "${w}, %e" ./bin/julia -width ${w} > /dev/null 2> line.csv
    cat line.csv >> all.csv
done
````
The trickery in the format string of "${w}, %e" should theoretically print both
the dependent and independent variable, though I haven't tested it.
