### ISSUE TITLE
Content of deliverables for cw1

### ISSUE THREAD

**Issue by malharjajoo** [HPCE/hpce-2017-cw1#51]
Hi,

I was wondering if anyone knew whether we are required to **explain** the result ( eg:- why parallel_inner is better than parallel_outer,etc ) for the last 4 pdfs ? 

Thanks

**Comment by m8pple** [comment]
As long as you try to explain the behaviour you see to yourself (or each
other), then that's fine, you don't need to write it down.

Different people will probably see slight differences, and may need to
come up with different parameters. It's also worth thinking about what
happens for other extreme parameters, in particular as you bring
each dependent value down to it's lowest possible value. You've got
a multi-dimensional parameter space, so if you pick difference baseline
points you'll see different effects as you sweep parameters.
