### ISSUE TITLE
Evaluating the speed-up - should I leave optimisation on?

### ISSUE THREAD

**Issue by aDu** [HPCE/hpce-2017-cw1#54]
I was wondering whether I should leave optimisation (`-DNDEBUG=1 -O3`) on when doing the final tasks (producing the graphs for comparing the four implementations)?

Thank you!

**Comment by m8pple** [comment]
Yes, you definitely want optimisations turned on.

The only time you should be disabling optimisations is during development and when debugging;
you want to be measuring "release" builds.

`NDEBUG=1` is a bit more contentious - I'm of the opinion that `assert` should be disabled in
release mode, particularly for anything high performance. People writing line-of-business
applications sometimes have different ideas though.
