### ISSUE TITLE
Mac OS Submission test_submission.sh change

### ISSUE THREAD

**Issue by Afraz496** [HPCE/hpce-2017-cw1#56]
Platform: MAC OS
Hi! I’ve submitted the zip file on blackboard including the edited test_submission.sh using gdate as mentioned in #41. Will there be any issues in running the script on the platform that will be used to check the coursework?

**Comment by m8pple** [comment]
Yes, that should be fine, as I'll use an original copy of the script.

The key thing that needs to complete is the `make bin/julia` part, which
relies on the makefile that you submitted. So as long as you haven't
added any OSX-specific stuff (which I don't think you need to), then
it should all be fine.

That said - if there is some trivial environmental mis-match that stops it
working, you won't get zero (particularly for CW1-CW4). I'll go in and
fix any minor config problems (which is usually solved just by over-writing
the makefile). However, if it clearly couldn't have worked on _any_ platform,
then people might start losing marks.
