### ISSUE TITLE
Microsoft Excel graphs 

### ISSUE THREAD

**Issue by sclimpro** [HPCE/hpce-2017-cw1#57]
Hi, I'm intending to print graphs in PDF using Microsoft Excel. How should I find out if it's 'vector graphics, not bitmap'?

**Comment by m8pple** [comment]
If you can [do this](https://www.youtube.com/watch?v=qHepKd38pr0), then it is a vector format.
You'll probably need to use a mouse and keyboard though, I don't think voice control is up
to it yet.

Usually `ctrl`+`+` works, or often `ctrl`+mousewheel. If it doesn't dissolve into blocks/pixels or
get blurry, then you've got a vector format.

In my experience excel should produce vector-based pdfs (though often its default
settings are a bit cartoonish/garish for academic work - a separate issue).

If you can't convince it to produce vector formats then don't worry too much. Bitmapped
graphs are somewhat acceptable as long as they are not too blurry or low-resolution.
