### ISSUE TITLE
Randomly failing tests 10 and or test 13

### ISSUE THREAD

**Issue by Afraz496** [HPCE/hpce-2017-cw1#59]
Platform: MAC OS

Hi, my code randomly fails tests 10 and 13. One instance of running it produced the following:
<img width="572" alt="screenshot 2017-10-19 19 01 15" src="https://user-images.githubusercontent.com/24629174/31786368-28fd31d2-b500-11e7-9476-a8249fe5a443.png">

<img width="570" alt="screenshot 2017-10-19 19 01 45" src="https://user-images.githubusercontent.com/24629174/31786377-2fb5e2d0-b500-11e7-8230-2cfeb1e25174.png">

And then running it immediately afterwards passed all tests:

<img width="570" alt="screenshot 2017-10-19 19 01 55" src="https://user-images.githubusercontent.com/24629174/31786393-3b047d90-b500-11e7-9427-a96aa9c5b652.png">

where the same test reads:

<img width="567" alt="screenshot 2017-10-19 19 04 16" src="https://user-images.githubusercontent.com/24629174/31786426-585f51f8-b500-11e7-9a08-6ea92a4573d4.png">

where there's an appreciable difference between the wide output reference time. 

Test 13 was also failing continuously, then I disconnected my phone and external displays and it passed flawlessly afterwards. Is my platform the result of these errors? Also, why do they occur sporadically? If anyone can help I would really appreciate it!

**Comment by m8pple** [comment]
Hrmm, not sure. Are you sure there are no background processes jumping in
and using CPU or disk? For example background things like indexers could
be interfering - watching the CPU usage while it executes might help, and
see if any other processes (including system processes) are using CPU. It could
be a frequency scaling problem, but doesn't quite feel like it's on the right time
scale, and the numbers aren't moving in the right direction. However,
OSX might be doing something complicated. One thing you could try is to fiddle with
`test_submission.sh` and swap the order it executes them in.

The phone/peripheral thing sounds fun - it is possibly some kind of background load due
to drivers or helper software, as some device drivers are far too "chatty", and send huge
amounts of tiny bits of data causing lots of interrupt traffic.

It sounds very much like a problem of consistency in your environment, so it should not
be a problem in my testing environment.
