### ISSUE TITLE
All of my parallel implementations have same output

### ISSUE THREAD

**Issue by t-sujone** [HPCE/hpce-2017-cw1#60]
I was happily running lots of commands thinking maybe this was what was supposed to happen, but then flicked back to the instructions which say sometimes outer is better and sometimes inner, and some of the comments on here say the time for max frames jumps at a certain value. 

All of my parallel/outer/inner/both output roughly the same times (lower than reference, but the same amount lower at each point) and I can increase max frames to some ridiculous number and the time stays pretty much constant at about 0.5ish... any ideas what I'm doing wrong?

**Comment by gglou** [comment]
Did you set the -animation flag for the max frames?

**Comment by t-sujone** [comment]
No i did not. so that solves that mystery. Do I need to include the max frames flag when running fr hieght/width/iter?

**Comment by m8pple** [comment]
Sorry, I missed the second question. Closing it as presumably it was resolved.
