### ISSUE TITLE
Personal Repos

### ISSUE THREAD

**Issue by luisi-at** [HPCE/hpce-2017-cw1#63]
Have the `https://github.com/HPCE/hpce-2018-cw1-[MY_LOGIN]` repositories been created yet? I haven't received any email indicating I've had a repo created with my git name yet, was wondering if I was missing something.

**Comment by jjd06** [comment]
Not yet. There's nothing stopping you from getting started in the meantime -- you can add `https://github.com/HPCE/hpce-2018-cw1-[MY_LOGIN]` as a remote to a local repo later.

**Comment by jjd06** [comment]
Now created.
