### ISSUE TITLE
Error with the test submission script timing analysis

### ISSUE THREAD

**Issue by luisi-at** [HPCE/hpce-2017-cw1#67]
I'm getting exactly the same times for the parallel and reference `wide` and `tall` runs in the submission script, which the script then fails:

<img width="676" alt="image" src="https://user-images.githubusercontent.com/17338500/51483825-db67ff00-1d91-11e9-8221-6e4527da907c.png">

The code is passing the calls for the `tbb::parallel_for` and there is a definite difference in speed- I'm wondering if this is an issue with the way the start and end times are calculated?

Info: macOS Mojave, 10.14 using Bash with homebrew

**Comment by luisi-at** [comment]
Ok, seems this is a macOS/OS X-related issue. I just tried using an Ubuntu 16.04 VM and all the tests passed. I'm interested to see if anyone else has experienced this on macOS/OS X.

**Comment by ashleydavies** [comment]
Also experiencing on MacOS; I didn't look into it too much but I consistently fail those tests too.

**Comment by jjd06** [comment]
There have been reported peculiarities of OS X's `date` handling before: see e.g. #27 for a similar previous report and suggested workaround. The assessment environment is Ubuntu 16, which doesn't have this problem.

**Comment by luisi-at** [comment]
Closing this due to previous issue and successful run on Ubuntu 16.
