### ISSUE TITLE
 CW1 - Making things parallel

### ISSUE THREAD

**Issue by andreamifsud** [HPCE/hpce-2017-cw1#9]
In the section

> Making things parallel (again)
> 
> Task:  Create an implementation called juliaFrameRender_ParallelInner in src/julia_frame_parallel_outer.cpp which parallelises the outer loop.

I think that juliaFrameRender_ParallelInner should be juliaFrameRender_ParallelOuter.

Additionally in section

> Evaluating the speed-up

What are the base-line parameters used for? For instance, taking the following task:

> Task: Evaluate the scaling with width, and save as results/scaling_width.pdf.

Should one set values of height =512, max-iter =512, max-frames =1 and sweep the width? I am asking as setting max-iter to 512 results in small execution times.

**Comment by m8pple** [comment]
> juliaFrameRender_ParallelInner should be juliaFrameRender_ParallelOuter.

Yes, you're right. Thanks.

Regarding the parameter sweeps, I'm not quite sure which part you're questioning.

By baseline, I mean "if this parameter is not otherwise specified, use this value". So
yes, I agree with this:

> Should one set values of height =512, max-iter =512, max-frames =1 and sweep the width?

If you change the width, you should be able to get a wide range of execution times

**Comment by andreamifsud** [comment]
ok thanks :)

**Comment by m8pple** [comment]
Actually, I think where I said "default width and height" is a bit mis-leading, I should have said
"baseline" for consistency.

**Comment by andreamifsud** [comment]
So should we use the default, or the baseline in that case?

**Comment by m8pple** [comment]
The baseline. Apologies if you did it with the program default already.
